// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The `Author` should be a string with format `Author Name <emabil@example.com>`
 *
 * The space between Author name and `<` must not be omitted.The author name can not contains `<` or `>`.
 *
 * We use [::email_address::EmailAddress::from_str] to check input email address.
 */
export type Author = `${string} <${string}@${string}>`;
