// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigDefault } from "./config_default.d";
import type { ConfigType } from "./config_type.d";

export type ConfigValue = { type: ConfigType; default: ConfigDefault };
