// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigOperation } from "./config_operation.d";

export type ConfigDefault =
  | `${string}:${string}`
  | { string: string }
  | boolean
  | bigint
  | ConfigOperation;
