// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一个包的来源
 */
export type PackageSource =
  | { package: string }
  | {
    /**
     * Url of the repo
     */
    repo: string;
    checkout?: string;
  }
  | { url: string }
  | { path: string };
