// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The source of a package.
 *
 * Its path should be relative path, relative to the project root.
 *
 * Use it to calculate hash, not [ResolvedPackageSource].
 */
export type PackageSource =
  | { package: string }
  | {
    /**
     * Url of the repo
     */
    repo: string;
    checkout?: string;
  }
  | { url: string }
  | { path: string };
