// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The pattern to match file paths.
 */
export type Pattern = Array<string> | {
  includes: Array<string>;
  excludes?: Array<string>;
  auto_suffix?: boolean;
} | { files: Array<string> };
