// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Author } from "./author.d";
import type { ConfigValue } from "./config_value.d";
import type { PackageSource } from "./dependency_source.d";
import type { Pattern } from "./pattern.d";

export type Project = {
  group: string;
  artifact?: string;
  version: string;
  configure_script?: string;
  description?: string;
  authors?: Array<Author>;
  license?: string;
  builds?: Pattern;
  rules?: Pattern;
  toolchains?: Pattern;
  subprojects?: Pattern;
  /**
   * The key will be checked by [crate::id::is_xid_loose_ident]
   */
  dependencies?: { [key in string]?: PackageSource };
  /**
   * Default mount config to `config`
   */
  mount_config?: string;
  /**
   * The key will be checked by [crate::id::is_xid_loose_ident]
   */
  config?: { [key in string]?: ConfigValue };
};
