// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Author } from "./author.d";
import type { Pattern } from "./pattern.d";

export type Project = {
  group: string;
  artifact: string;
  version: string;
  description?: string;
  authors?: Array<Author>;
  license?: string;
  builds?: Pattern;
  rules?: Pattern;
  toolchains?: Pattern;
  subprojects?: Pattern;
};
